// import 'package:flutter/material.dart';

class Products {
  int? id;
  String? title;
  String? imageUrl1;
  String? desc;
  double? cost;
  int? discount;
  int? qountity;
  String? brand;
  String? rating;
  String? colors;
  Products({
    this.id,
    this.title,
    this.imageUrl1,
    this.desc,
    this.cost,
    this.discount,
    this.qountity,
    this.brand,
    this.rating,
    this.colors,
  });
}

class ProdustListing {
  static List<Products> phoneList = [
    Products(
        id: 1,
        title: 'iphone 13 pro',
        imageUrl1: 'assets/images/iphone13_1.jpg',
        desc:
            'The iPhone 13 Pro and Pro Max use an Apple-designed A15 Bionic processor featuring a 16-core neural engine, 6-core CPU (with 2 performance cores and 4 efficiency cores), and 5-core GPU. The A15 Bionic also contains a next-generation image processor.',
        cost: 1900,
        brand: 'Iphone',
        colors: 'Blue',
        discount: 10,
        qountity: 8,
        rating: '4.9'),
    Products(
        id: 2,
        title: 'Iphone 12 pro',
        imageUrl1: 'assets/images/iphone12_1.jpg',
        desc:
            "The iPhone 12 Pro uses Apple's six-core A14 Bionic processor, which contains a 16-core neural engine. It has three internal storage options: 128, 256, and 512 GB. The iPhone 12 Pro has an IP68 water and dust-resistant rating along with dirt and grime, and is water-resistant up to six meters (20 feet) for 30 minutes.",
        cost: 1500,
        brand: 'Iphone',
        colors: 'Black',
        discount: 10,
        qountity: 8,
        rating: '4.7'),
    Products(
        id: 3,
        title: 'Realme narzo 50',
        imageUrl1: 'assets/images/realme1.jpg',
        desc:
            'The iPhone 13 Pro and Pro Max use an Apple-designed A15 Bionic processor featuring a 16-core neural engine, 6-core CPU (with 2 performance cores and 4 efficiency cores), and 5-core GPU. The A15 Bionic also contains a next-generation image processor.',
        cost: 950,
        brand: 'Realme',
        colors: 'Black',
        discount: 10,
        qountity: 8,
        rating: '4.8'),
    Products(
        id: 4,
        title: 'Oppo a16',
        imageUrl1: 'assets/images/oppo1.jpg',
        desc:
            'Camera. Rear 13MP Main Camera: f/2.2; FOV 80°; 5P lens; AF 2MP Mono Camera: f/2.4; FOV 88.8°; 3P lens; FF 2MP Macro Camera: f/2.4; FOV 88.8°; 3P lens.',
        cost: 900,
        brand: 'Oppo',
        colors: 'Silver',
        discount: 10,
        qountity: 6,
        rating: '4.6'),
    Products(
        id: 5,
        title: 'Samsung galaxy A16',
        imageUrl1: 'assets/images/samsung1.jpg',
        desc:
            'Exynos 1380, Octa Core, 2.4 GHz Processor, 8 GB RAM, 128 GB inbuilt, 8 GB RAM, 128 GB inbuilt, 50 MP + 12 MP + 5 MP Triple Rear & 32 MP Front Camera.',
        cost: 800,
        brand: 'Samsung',
        colors: 'Black',
        discount: 10,
        qountity: 4,
        rating: '4.4'),
    Products(
        id: 6,
        title: 'Huawei p60 pro',
        imageUrl1: 'assets/images/huawei1.jpg',
        desc:
            'With a rounded corners design on the display, the diagonal length of the exterior screen is 6.67 inches when measured according to the standard rectangle (the actual viewable area is slightly smaller).',
        cost: 750,
        brand: 'Huawei',
        colors: 'White',
        discount: 10,
        qountity: 7,
        rating: '4.8'),
    Products(
        id: 7,
        title: 'vivo v23 pro',
        imageUrl1: 'assets/images/vivo1.jpg',
        desc:
            'Exynos 1380, Octa Core, 2.4 GHz Processor, 8 GB RAM, 128 GB inbuilt, 8 GB RAM, 128 GB inbuilt, 50 MP + 12 MP + 5 MP Triple Rear & 32 MP Front Camera.',
        cost: 750,
        brand: 'Vivo',
        colors: 'Goldern',
        discount: 10,
        qountity: 15,
        rating: '4.9'),
  ];

  static List<Products> menswearlist = [
    Products(
        id: 8,
        title: 'Mens branded shirt',
        imageUrl1: 'assets/images/shirt1.jpg',
        desc: 'Essential mens shirts avaible',
        cost: 47,
        brand: 'Eagle',
        colors: 'Black',
        discount: 5,
        qountity: 15,
        rating: '4.7'),
    Products(
        id: 9,
        title: 'Mens branded shirt',
        imageUrl1: 'assets/images/blue1.jpg',
        desc: 'Essential mens shirts avaible',
        cost: 50,
        brand: 'Eagle',
        colors: 'Blue',
        discount: 5,
        qountity: 18,
        rating: '4.7'),
    Products(
        id: 10,
        title: 'Mens branded pant',
        imageUrl1: 'assets/images/blackpant1.jpg',
        desc: 'Essential mens pant avaible',
        cost: 40,
        brand: 'Eagle',
        colors: 'Black',
        discount: 5,
        qountity: 15,
        rating: '4.7'),
    Products(
        id: 11,
        title: 'Mens branded pant',
        imageUrl1: 'assets/images/pantblue1.jpg',
        desc: 'Essential mens pant avaible',
        cost: 75,
        brand: 'Eagle',
        colors: 'Black',
        discount: 5,
        qountity: 15,
        rating: '4.7'),
    Products(
        id: 12,
        title: 'Mens branded Jacket',
        imageUrl1: 'assets/images/jacket1.jpg',
        desc: 'Essential mens Jacket avaible',
        cost: 179.99,
        brand: 'Eagle',
        colors: 'Black',
        discount: 5,
        qountity: 15,
        rating: '4.7'),
    Products(
        id: 13,
        title: 'Mens branded Coat',
        imageUrl1: 'assets/images/coat1.jpg',
        desc: 'Essential mens Coat avaible',
        cost: 120,
        brand: 'Eagle',
        colors: 'Black',
        discount: 5,
        qountity: 15,
        rating: '4.7'),
    Products(
        id: 14,
        title: 'Mens branded lofar',
        imageUrl1: 'assets/images/show1.jpg',
        desc: 'Essential mens lofar avaible',
        cost: 145,
        brand: 'Nike',
        colors: 'Black',
        discount: 5,
        qountity: 15,
        rating: '4.7'),
    Products(
        id: 15,
        title: 'Mens branded nike shows',
        imageUrl1: 'assets/images/nike1.jpg',
        desc: 'Essential mens nike shows avaible',
        cost: 210,
        brand: 'Nike',
        colors: 'Black',
        discount: 5,
        qountity: 15,
        rating: '4.8'),
  ];

  static List<Products> womenswearlist = [
    Products(
        id: 16,
        title: 'Ladies loan sout',
        imageUrl1: 'assets/images/female1.jpg',
        cost: 100,
        brand: "Sana Sufina's",
        colors: 'Red',
        discount: 15,
        qountity: 10,
        rating: '4.9'),
    Products(
        id: 17,
        title: 'Ladies branded zayden',
        imageUrl1: 'assets/images/zayden1.jpg',
        desc: 'Essential femens zayden avaible',
        cost: 80,
        brand: 'American',
        colors: 'White',
        discount: 5,
        qountity: 18,
        rating: '4.8'),
    Products(
        id: 18,
        title: 'Ladies branded vintage',
        imageUrl1: 'assets/images/vintage1.jpg',
        desc: 'Essential ladies vintage avaible',
        cost: 100,
        brand: 'Eagle',
        colors: 'Blue',
        discount: 5,
        qountity: 15,
        rating: '4.7'),
    Products(
        id: 19,
        title: 'Ladies branded hound',
        imageUrl1: 'assets/images/hound1.jpg',
        desc: 'Essential mens hound avaible',
        cost: 169.99,
        brand: 'Eagle',
        colors: 'Black',
        discount: 5,
        qountity: 15,
        rating: '4.7'),
    Products(
        id: 20,
        title: 'Ladies branded hoodie',
        imageUrl1: 'assets/images/hoodie.jpg',
        desc: 'Essential mens hoodie avaible',
        cost: 183.99,
        brand: 'Eagle',
        colors: 'Black',
        discount: 5,
        qountity: 15,
        rating: '4.7'),
    Products(
        id: 21,
        title: 'Ladies branded ladies sandle',
        imageUrl1: 'assets/images/ladiesshow1.jpg',
        desc: 'Essential mens ladies sandle avaible',
        cost: 150.99,
        brand: 'Eagle',
        colors: 'Black',
        discount: 5,
        qountity: 15,
        rating: '4.7'),
    Products(
        id: 22,
        title: 'Ladies branded Pack',
        imageUrl1: 'assets/images/pack1.jpg',
        desc: 'Essential mens Pack avaible',
        cost: 110.99,
        brand: 'Nike',
        colors: 'Black',
        discount: 5,
        qountity: 15,
        rating: '4.7'),
  ];
  static List<Products> furniturelist = [
    Products(
        id: 23,
        title: 'Queen Size Upholstered Platform Bed',
        imageUrl1: 'assets/images/bed.jpg',
        desc:
            'Queen Size Upholstered Platform Bed Frame with Headboard, Strong Wood Slat Support, Mattress Foundation, No Box Spring Needed, Easy Assembly, Gray',
        cost: 225,
        brand: "non",
        colors: 'Grey',
        discount: 15,
        qountity: 10,
        rating: '4.9'),
    Products(
        id: 24,
        title: 'Our favourite wooden armchairs',
        imageUrl1: 'assets/images/chair.jpg',
        desc:
            'Finishing: dark walnut. Seating Dimensions - 17.16 High (from Floor) x 20.09 Wide x 20.28 Long Inch. Arm Height- 6.05 High. From Floor to top of arms - 22.43 High',
        cost: 123,
        brand: 'American',
        colors: 'White',
        discount: 5,
        qountity: 18,
        rating: '4.8'),
    Products(
        id: 25,
        title: 'Nordic Arm Sofa',
        imageUrl1: 'assets/images/sofa.jpg',
        desc:
            'We can customize this product upon your request.All covers include their foam filling inserts All covers are zippered Beautiful texture and soft to touch Comfortable to sit or sleep on Top-quality finish and workmanship Excellent for homes, offices, hotels, cafeterias, etc.Machine washable',
        cost: 1349,
        brand: 'Eagle',
        colors: 'Blue',
        discount: 5,
        qountity: 15,
        rating: '4.7'),
    Products(
        id: 26,
        title: 'Center table',
        imageUrl1: 'assets/images/table.jpg',
        desc: 'Essential table avaible',
        cost: 680,
        brand: 'Eagle',
        colors: 'Black',
        discount: 5,
        qountity: 15,
        rating: '4.7'),
    Products(
        id: 27,
        title: 'Recliner Chair',
        imageUrl1: 'assets/images/recycle.jpg',
        desc: 'Essential Chair avaible',
        cost: 1320,
        brand: 'Eagle',
        colors: 'Black',
        discount: 5,
        qountity: 15,
        rating: '4.7'),
    Products(
        id: 28,
        title: 'Bookcase',
        imageUrl1: 'assets/images/bookcase.jpg',
        desc: 'Essential Bookcaseavaible',
        cost: 999,
        brand: 'Eagle',
        colors: 'Black',
        discount: 5,
        qountity: 15,
        rating: '4.7'),
    Products(
        id: 29,
        title: 'Wallpanel',
        imageUrl1: 'assets/images/wallpanel.jpg',
        desc: 'Wallpanel avaible',
        cost: 830,
        brand: 'Nike',
        colors: 'Black',
        discount: 5,
        qountity: 15,
        rating: '4.7'),
  ];
  static List<Products> homeApplianceslist = [
    Products(
        id: 30,
        title: 'Juicer',
        imageUrl1: 'assets/images/juicer.jpg',
        desc:
            'Queen Size Upholstered Platform Bed Frame with Headboard, Strong Wood Slat Support, Mattress Foundation, No Box Spring Needed, Easy Assembly, Gray',
        cost: 879,
        brand: "non",
        colors: 'Grey',
        discount: 15,
        qountity: 10,
        rating: '4.9'),
    Products(
        id: 31,
        title: 'Full size oven',
        imageUrl1: 'assets/images/oven.jpg',
        desc:
            'Finishing: dark walnut. Seating Dimensions - 17.16 High (from Floor) x 20.09 Wide x 20.28 Long Inch. Arm Height- 6.05 High. From Floor to top of arms - 22.43 High',
        cost: 2100,
        brand: 'American',
        colors: 'White',
        discount: 5,
        qountity: 18,
        rating: '4.8'),
    Products(
        id: 32,
        title: 'Blender',
        imageUrl1: 'assets/images/blender.jpg',
        desc:
            'We can customize this product upon your request.All covers include their foam filling inserts All covers are zippered Beautiful texture and soft to touch Comfortable to sit or sleep on Top-quality finish and workmanship Excellent for homes, offices, hotels, cafeterias, etc.Machine washable',
        cost: 1190,
        brand: 'Eagle',
        colors: 'Blue',
        discount: 5,
        qountity: 15,
        rating: '4.7'),
    Products(
        id: 33,
        title: 'Samsung Smart Referigerator',
        imageUrl1: 'assets/images/referigerator.jpg',
        desc: 'Samsung Smart Referigerator avaible',
        cost: 5600,
        brand: 'Eagle',
        colors: 'Black',
        discount: 5,
        qountity: 15,
        rating: '4.7'),
    Products(
        id: 34,
        title: 'Cutlery Set',
        imageUrl1: 'assets/images/cutlery.jpg',
        desc: 'Cutlery Set avaible',
        cost: 1710,
        brand: 'Eagle',
        colors: 'Black',
        discount: 5,
        qountity: 15,
        rating: '4.7'),
    Products(
        id: 35,
        title: 'Smart Washing Machine',
        imageUrl1: 'assets/images/washingMachine.jpg',
        desc: 'Smart Washing Machine avaible',
        cost: 3500,
        brand: 'Eagle',
        colors: 'Black',
        discount: 5,
        qountity: 15,
        rating: '4.7'),
    Products(
        id: 36,
        title: 'Iron',
        imageUrl1: 'assets/images/iron.jpg',
        desc: 'Iron avaible',
        cost: 830,
        brand: 'Nike',
        colors: 'Black',
        discount: 5,
        qountity: 15,
        rating: '4.7'),
  ];

  static List<Products> searchList = [
    Products(
        id: 1,
        title: 'iphone 13 pro',
        imageUrl1: 'assets/images/iphone13_1.jpg',
        desc:
            'The iPhone 13 Pro and Pro Max use an Apple-designed A15 Bionic processor featuring a 16-core neural engine, 6-core CPU (with 2 performance cores and 4 efficiency cores), and 5-core GPU. The A15 Bionic also contains a next-generation image processor.',
        cost: 1900,
        brand: 'Iphone',
        colors: 'Blue',
        discount: 10,
        qountity: 8,
        rating: '4.9'),
    Products(
        id: 2,
        title: 'Iphone 12 pro',
        imageUrl1: 'assets/images/iphone12_1.jpg',
        desc:
            "The iPhone 12 Pro uses Apple's six-core A14 Bionic processor, which contains a 16-core neural engine. It has three internal storage options: 128, 256, and 512 GB. The iPhone 12 Pro has an IP68 water and dust-resistant rating along with dirt and grime, and is water-resistant up to six meters (20 feet) for 30 minutes.",
        cost: 1500,
        brand: 'Iphone',
        colors: 'Black',
        discount: 10,
        qountity: 8,
        rating: '4.7'),
    Products(
        id: 3,
        title: 'Realme narzo 50',
        imageUrl1: 'assets/images/realme1.jpg',
        desc:
            'The iPhone 13 Pro and Pro Max use an Apple-designed A15 Bionic processor featuring a 16-core neural engine, 6-core CPU (with 2 performance cores and 4 efficiency cores), and 5-core GPU. The A15 Bionic also contains a next-generation image processor.',
        cost: 950,
        brand: 'Realme',
        colors: 'Black',
        discount: 10,
        qountity: 8,
        rating: '4.8'),
    Products(
        id: 4,
        title: 'Oppo a16',
        imageUrl1: 'assets/images/oppo1.jpg',
        desc:
            'Camera. Rear 13MP Main Camera: f/2.2; FOV 80°; 5P lens; AF 2MP Mono Camera: f/2.4; FOV 88.8°; 3P lens; FF 2MP Macro Camera: f/2.4; FOV 88.8°; 3P lens.',
        cost: 900,
        brand: 'Oppo',
        colors: 'Silver',
        discount: 10,
        qountity: 6,
        rating: '4.6'),
    Products(
        id: 5,
        title: 'Samsung galaxy A16',
        imageUrl1: 'assets/images/samsung1.jpg',
        desc:
            'Exynos 1380, Octa Core, 2.4 GHz Processor, 8 GB RAM, 128 GB inbuilt, 8 GB RAM, 128 GB inbuilt, 50 MP + 12 MP + 5 MP Triple Rear & 32 MP Front Camera.',
        cost: 800,
        brand: 'Samsung',
        colors: 'Black',
        discount: 10,
        qountity: 4,
        rating: '4.4'),
    Products(
        id: 6,
        title: 'Huawei p60 pro',
        imageUrl1: 'assets/images/huawei1.jpg',
        desc:
            'With a rounded corners design on the display, the diagonal length of the exterior screen is 6.67 inches when measured according to the standard rectangle (the actual viewable area is slightly smaller).',
        cost: 750,
        brand: 'Huawei',
        colors: 'White',
        discount: 10,
        qountity: 7,
        rating: '4.8'),
    Products(
        id: 7,
        title: 'vivo v23 pro',
        imageUrl1: 'assets/images/vivo1.jpg',
        desc:
            'Exynos 1380, Octa Core, 2.4 GHz Processor, 8 GB RAM, 128 GB inbuilt, 8 GB RAM, 128 GB inbuilt, 50 MP + 12 MP + 5 MP Triple Rear & 32 MP Front Camera.',
        cost: 750,
        brand: 'Vivo',
        colors: 'Goldern',
        discount: 10,
        qountity: 15,
        rating: '4.9'),
    Products(
        id: 8,
        title: 'Mens branded shirt',
        imageUrl1: 'assets/images/shirt1.jpg',
        desc: 'Essential mens shirts avaible',
        cost: 47,
        brand: 'Eagle',
        colors: 'Black',
        discount: 5,
        qountity: 15,
        rating: '4.7'),
    Products(
        id: 9,
        title: 'Mens branded shirt',
        imageUrl1: 'assets/images/blue1.jpg',
        desc: 'Essential mens shirts avaible',
        cost: 50,
        brand: 'Eagle',
        colors: 'Blue',
        discount: 5,
        qountity: 18,
        rating: '4.7'),
    Products(
        id: 10,
        title: 'Mens branded pant',
        imageUrl1: 'assets/images/blackpant1.jpg',
        desc: 'Essential mens pant avaible',
        cost: 40,
        brand: 'Eagle',
        colors: 'Black',
        discount: 5,
        qountity: 15,
        rating: '4.7'),
    Products(
        id: 11,
        title: 'Mens branded pant',
        imageUrl1: 'assets/images/pantblue1.jpg',
        desc: 'Essential mens pant avaible',
        cost: 75,
        brand: 'Eagle',
        colors: 'Black',
        discount: 5,
        qountity: 15,
        rating: '4.7'),
    Products(
        id: 12,
        title: 'Mens branded Jacket',
        imageUrl1: 'assets/images/jacket1.jpg',
        desc: 'Essential mens Jacket avaible',
        cost: 179.99,
        brand: 'Eagle',
        colors: 'Black',
        discount: 5,
        qountity: 15,
        rating: '4.7'),
    Products(
        id: 13,
        title: 'Mens branded Coat',
        imageUrl1: 'assets/images/coat1.jpg',
        desc: 'Essential mens Coat avaible',
        cost: 120,
        brand: 'Eagle',
        colors: 'Black',
        discount: 5,
        qountity: 15,
        rating: '4.7'),
    Products(
        id: 14,
        title: 'Mens branded lofar',
        imageUrl1: 'assets/images/show1.jpg',
        desc: 'Essential mens lofar avaible',
        cost: 145,
        brand: 'Nike',
        colors: 'Black',
        discount: 5,
        qountity: 15,
        rating: '4.7'),
    Products(
        id: 15,
        title: 'Mens branded nike shows',
        imageUrl1: 'assets/images/nike1.jpg',
        desc: 'Essential mens nike shows avaible',
        cost: 210,
        brand: 'Nike',
        colors: 'Black',
        discount: 5,
        qountity: 15,
        rating: '4.8'),
    Products(
        id: 16,
        title: 'Ladies loan sout',
        imageUrl1: 'assets/images/female1.jpg',
        cost: 100,
        brand: "Sana Sufina's",
        colors: 'Red',
        discount: 15,
        qountity: 10,
        rating: '4.9'),
    Products(
        id: 17,
        title: 'Ladies branded zayden',
        imageUrl1: 'assets/images/zayden1.jpg',
        desc: 'Essential femens zayden avaible',
        cost: 80,
        brand: 'American',
        colors: 'White',
        discount: 5,
        qountity: 18,
        rating: '4.8'),
    Products(
        id: 18,
        title: 'Ladies branded vintage',
        imageUrl1: 'assets/images/vintage1.jpg',
        desc: 'Essential ladies vintage avaible',
        cost: 100,
        brand: 'Eagle',
        colors: 'Blue',
        discount: 5,
        qountity: 15,
        rating: '4.7'),
    Products(
        id: 19,
        title: 'Ladies branded hound',
        imageUrl1: 'assets/images/hound1.jpg',
        desc: 'Essential mens hound avaible',
        cost: 169.99,
        brand: 'Eagle',
        colors: 'Black',
        discount: 5,
        qountity: 15,
        rating: '4.7'),
    Products(
        id: 20,
        title: 'Ladies branded hoodie',
        imageUrl1: 'assets/images/hoodie.jpg',
        desc: 'Essential mens hoodie avaible',
        cost: 183.99,
        brand: 'Eagle',
        colors: 'Black',
        discount: 5,
        qountity: 15,
        rating: '4.7'),
    Products(
        id: 21,
        title: 'Ladies branded ladies sandle',
        imageUrl1: 'assets/images/ladiesshow1.jpg',
        desc: 'Essential mens ladies sandle avaible',
        cost: 150.99,
        brand: 'Eagle',
        colors: 'Black',
        discount: 5,
        qountity: 15,
        rating: '4.7'),
    Products(
        id: 22,
        title: 'Ladies branded Pack',
        imageUrl1: 'assets/images/pack1.jpg',
        desc: 'Essential mens Pack avaible',
        cost: 110.99,
        brand: 'Nike',
        colors: 'Black',
        discount: 5,
        qountity: 15,
        rating: '4.7'),
    Products(
        id: 23,
        title: 'Queen Size Upholstered Platform Bed',
        imageUrl1: 'assets/images/bed.jpg',
        desc:
            'Queen Size Upholstered Platform Bed Frame with Headboard, Strong Wood Slat Support, Mattress Foundation, No Box Spring Needed, Easy Assembly, Gray',
        cost: 225,
        brand: "non",
        colors: 'Grey',
        discount: 15,
        qountity: 10,
        rating: '4.9'),
    Products(
        id: 24,
        title: 'Our favourite wooden armchairs',
        imageUrl1: 'assets/images/chair.jpg',
        desc:
            'Finishing: dark walnut. Seating Dimensions - 17.16 High (from Floor) x 20.09 Wide x 20.28 Long Inch. Arm Height- 6.05 High. From Floor to top of arms - 22.43 High',
        cost: 550,
        brand: 'American',
        colors: 'White',
        discount: 5,
        qountity: 18,
        rating: '4.8'),
    Products(
        id: 25,
        title: 'Nordic Arm Sofa',
        imageUrl1: 'assets/images/sofa.jpg',
        desc:
            'We can customize this product upon your request.All covers include their foam filling inserts All covers are zippered Beautiful texture and soft to touch Comfortable to sit or sleep on Top-quality finish and workmanship Excellent for homes, offices, hotels, cafeterias, etc.Machine washable',
        cost: 1349,
        brand: 'Eagle',
        colors: 'Blue',
        discount: 5,
        qountity: 15,
        rating: '4.7'),
    Products(
        id: 26,
        title: 'Center table',
        imageUrl1: 'assets/images/table.jpg',
        desc: 'Essential table avaible',
        cost: 680,
        brand: 'Eagle',
        colors: 'Black',
        discount: 5,
        qountity: 15,
        rating: '4.7'),
    Products(
        id: 27,
        title: 'Recliner Chair',
        imageUrl1: 'assets/images/recycle.jpg',
        desc: 'Essential Chair avaible',
        cost: 1320,
        brand: 'Eagle',
        colors: 'Black',
        discount: 5,
        qountity: 15,
        rating: '4.7'),
    Products(
        id: 28,
        title: 'Bookcase',
        imageUrl1: 'assets/images/bookcase.jpg',
        desc: 'Essential Bookcaseavaible',
        cost: 999,
        brand: 'Eagle',
        colors: 'Black',
        discount: 5,
        qountity: 15,
        rating: '4.7'),
    Products(
        id: 29,
        title: 'Wallpanel',
        imageUrl1: 'assets/images/wallpanel.jpg',
        desc: 'Wallpanel avaible',
        cost: 830,
        brand: 'Nike',
        colors: 'Black',
        discount: 5,
        qountity: 15,
        rating: '4.7'),
    Products(
        id: 30,
        title: 'Juicer',
        imageUrl1: 'assets/images/juicer.jpg',
        desc:
            'Queen Size Upholstered Platform Bed Frame with Headboard, Strong Wood Slat Support, Mattress Foundation, No Box Spring Needed, Easy Assembly, Gray',
        cost: 879,
        brand: "non",
        colors: 'Grey',
        discount: 15,
        qountity: 10,
        rating: '4.9'),
    Products(
        id: 31,
        title: 'Full size oven',
        imageUrl1: 'assets/images/oven.jpg',
        desc:
            'Finishing: dark walnut. Seating Dimensions - 17.16 High (from Floor) x 20.09 Wide x 20.28 Long Inch. Arm Height- 6.05 High. From Floor to top of arms - 22.43 High',
        cost: 2100,
        brand: 'American',
        colors: 'White',
        discount: 5,
        qountity: 18,
        rating: '4.8'),
    Products(
        id: 32,
        title: 'Blender',
        imageUrl1: 'assets/images/blender.jpg',
        desc:
            'We can customize this product upon your request.All covers include their foam filling inserts All covers are zippered Beautiful texture and soft to touch Comfortable to sit or sleep on Top-quality finish and workmanship Excellent for homes, offices, hotels, cafeterias, etc.Machine washable',
        cost: 1190,
        brand: 'Eagle',
        colors: 'Blue',
        discount: 5,
        qountity: 15,
        rating: '4.7'),
    Products(
        id: 33,
        title: 'Samsung Smart Referigerator',
        imageUrl1: 'assets/images/referigerator.jpg',
        desc: 'Samsung Smart Referigerator avaible',
        cost: 5600,
        brand: 'Eagle',
        colors: 'Black',
        discount: 5,
        qountity: 15,
        rating: '4.7'),
    Products(
        id: 34,
        title: 'Cutlery Set',
        imageUrl1: 'assets/images/cutlery.jpg',
        desc: 'Cutlery Set avaible',
        cost: 1710,
        brand: 'Eagle',
        colors: 'Black',
        discount: 5,
        qountity: 15,
        rating: '4.7'),
    Products(
        id: 35,
        title: 'Smart Washing Machine',
        imageUrl1: 'assets/images/washingMachine.jpg',
        desc: 'Smart Washing Machine avaible',
        cost: 3500,
        brand: 'Eagle',
        colors: 'Black',
        discount: 5,
        qountity: 15,
        rating: '4.7'),
    Products(
        id: 36,
        title: 'Iron',
        imageUrl1: 'assets/images/iron.jpg',
        desc: 'Iron avaible',
        cost: 830,
        brand: 'Nike',
        colors: 'Black',
        discount: 5,
        qountity: 15,
        rating: '4.7'),
  ];

  static List<Products> quikOrder = [
    Products(
        id: 20,
        title: 'Ladies branded hoodie',
        imageUrl1: 'assets/images/hoodie.jpg',
        desc: 'Essential mens hoodie avaible',
        cost: 183.99,
        brand: 'Eagle',
        colors: 'Black',
        discount: 5,
        qountity: 15,
        rating: '4.7'),
    Products(
        id: 21,
        title: 'Ladies branded ladies sandle',
        imageUrl1: 'assets/images/ladiesshow1.jpg',
        desc: 'Essential mens ladies sandle avaible',
        cost: 150.99,
        brand: 'Eagle',
        colors: 'Black',
        discount: 5,
        qountity: 15,
        rating: '4.7'),
    Products(
        id: 6,
        title: 'Huawei p60 pro',
        imageUrl1: 'assets/images/huawei1.jpg',
        desc:
            'With a rounded corners design on the display, the diagonal length of the exterior screen is 6.67 inches when measured according to the standard rectangle (the actual viewable area is slightly smaller).',
        cost: 750,
        brand: 'Huawei',
        colors: 'White',
        discount: 10,
        qountity: 7,
        rating: '4.8'),
    Products(
        id: 7,
        title: 'vivo v23 pro',
        imageUrl1: 'assets/images/vivo1.jpg',
        desc:
            'Exynos 1380, Octa Core, 2.4 GHz Processor, 8 GB RAM, 128 GB inbuilt, 8 GB RAM, 128 GB inbuilt, 50 MP + 12 MP + 5 MP Triple Rear & 32 MP Front Camera.',
        cost: 750,
        brand: 'Vivo',
        colors: 'Goldern',
        discount: 10,
        qountity: 15,
        rating: '4.9'),
    Products(
        id: 26,
        title: 'Center table',
        imageUrl1: 'assets/images/table.jpg',
        desc: 'Essential table avaible',
        cost: 680,
        brand: 'Eagle',
        colors: 'Black',
        discount: 5,
        qountity: 15,
        rating: '4.7'),
    Products(
        id: 32,
        title: 'Blender',
        imageUrl1: 'assets/images/blender.jpg',
        desc:
            'We can customize this product upon your request.All covers include their foam filling inserts All covers are zippered Beautiful texture and soft to touch Comfortable to sit or sleep on Top-quality finish and workmanship Excellent for homes, offices, hotels, cafeterias, etc.Machine washable',
        cost: 1190,
        brand: 'Eagle',
        colors: 'Blue',
        discount: 5,
        qountity: 15,
        rating: '4.7'),
    Products(
        id: 21,
        title: 'Ladies branded ladies sandle',
        imageUrl1: 'assets/images/ladiesshow1.jpg',
        desc: 'Essential mens ladies sandle avaible',
        cost: 150.99,
        brand: 'Eagle',
        colors: 'Black',
        discount: 5,
        qountity: 15,
        rating: '4.7'),
    Products(
        id: 22,
        title: 'Ladies branded Pack',
        imageUrl1: 'assets/images/pack1.jpg',
        desc: 'Essential mens Pack avaible',
        cost: 110.99,
        brand: 'Nike',
        colors: 'Black',
        discount: 5,
        qountity: 15,
        rating: '4.7'),
  ];
}
